apiVersion: apps/v1
# Stateful is most appropriate
kind: Deployment
metadata:
  # Production non-common practice
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              #value: root_Pwd
              valueFrom:
                secretKeyRef:
                  name: mysql-dbpwd-secret
                  key: mysql-db-pwd
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
            - name: user-mgmt-dbscript-cm
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-csi-mysql-pvc
        - name: user-mgmt-dbscript-cm
          configMap:
            name: user-mgmt-dbscript-cm

