apiVersion: v1
kind: Pod

metadata:
  name: writer-watcher-apps-pod

spec:
  volumes:
    - name: shared-volume
      emptyDir: { }
      # tmpfs as fast as possible
      # medium: Memory
  containers:
    # Same for sample section 7.6 -> Creating a pod with two containers and a shared volume
    - name: watcher
      image: douglasdb/watcher
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp/lost/output/
          name: shared-volume
          # Optional
          #readOnly: true
    # ------------------------------------------------
    - name: writer
      image: douglasdb/writer
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp/lost/input/
          name: shared-volume