apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-csi-mysql-pvc
  namespace: k8s-inaction
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi