apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-svc
  namespace: k8s-inaction
  labels:
    app: user-mgmt-microservice-backend
spec:
  type: NodePort
  selector:
    app: user-mgmt-microservice-backend
  ports:
    - port: 8095 # app port
      targetPort: 8095 # container port
      #nodePort: 31231 # k8s exposed node port