apiVersion: v1
kind: Service
metadata:
  name: api-backend-v1-svc
  labels:
    app: api-backend-v1
    tier: backend
spec:
  type: NodePort
  selector:
    app: api-backend-v1
    tier: backend
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31231 # NodePort