apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-eksmaster-svc #
  labels:
    app: frontend-nginx-eksmaster
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginx-eksmaster
  ports:
    - name: http
      port: 8080 # ClusterIP service Port
      targetPort: 8080
      nodePort: 31234