apiVersion: v1
kind: Pod
metadata:
  name: app-backendv01-ch05
spec:
  containers:
    - name: app-backendv01-ch05
      image: douglasdb/app-backend-v1-native:1.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 12080