apiVersion: v1
kind: Pod
metadata:
  name: app-backendv01-ch05-ssl
spec:
  initContainers:
    - name: init-demo
      image: luksa/init-demo:0.1
    - name: network-check
      image: luksa/network-connectivity-checker:0.1
  containers:
    - name: app-backendv01-ch05-ssl
      #image: douglasdb/api-backend-v01-jvm:1.0
      image: douglasdb/app-backend-v1-native:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
    - name: envoy
      image: luksa/kiada-ssl-proxy:0.1
      ports:
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901
