apiVersion: v1
kind: Pod
metadata:
  labels:
    app: backend-api-ch05-liveness
  name: backend-api-ch05-liveness
spec:
  containers:
    - name: backend-api-ch05-liveness
      image: douglasdb/app-backend-v1-native:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 12080
        - name: health
          containerPort: 8080
      livenessProbe:
        httpGet:
          port: health
          path: /q/health
        initialDelaySeconds: 3
        periodSeconds: 3
        timeoutSeconds: 2
        failureThreshold: 3