apiVersion: v1
kind: Service
metadata:
  name: nlb-usermgmt-restapp-service
  labels:
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # create Network Load Balancer
spec:
  type: LoadBalancer # Default-Classic Load Balancer
  selector:
    app: usermgmt-restapp
  ports:
    - port: 80
      targetPort: 8095
      #nodePort: 31231