apiVersion: v1
kind: Pod

metadata:
  name: quiz-camel-mongodb-app
spec:
  volumes:
    - name: quiz-data
      emptyDir: {} #medium/memory - sizeLimit
  containers:
    - name: camel-mongodb-app
      image: douglasdb/mongodb-volume-native-app
      readinessProbe:
        tcpSocket:
          port: 27017
        initialDelaySeconds: 20
        periodSeconds: 10
      ports:
        - containerPort: 8080
          name: http
    - name: mongodb
      image: mongo
      volumeMounts:
        - mountPath: quiz-data
          name: /data/db