apiVersion: v1
kind: Pod

metadata:
  name: watcher-pod
spec:
  volumes:
    - name: shared-volume
      hostPath:
        path: /tmp
      #emptyDir: { }
      #tmpfs as fast as possible
      # medium: Memory
  containers:
    # Same for sample section 7.6 A pod with two containers that share a volume
    - name: watcher
      image: douglasdb/watcher
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp/lost/output/
          name: shared-volume
          readOnly: true
    # ------------------------------------------------
    #- name: camelapp-writer
    #  image: douglasdb/appv1-emptydir-write:2.0
    #  imagePullPolicy: Always
    #  volumeMounts:
    #    - mountPath: /tmp/lost/input/
    #      name: shared-volume