apiVersion: v1
kind: Pod

metadata:
  name: writer-watcher-pod
spec:
  volumes:
    - name: shared-volume
      # dangerous
      hostPath:
        path: /tmp
        type: DirectoryOrCreate
      #emptyDir: { }
      #tmpfs as fast as possible
      # medium: Memory
  containers:
    # Same for sample section 7.6 A pod with two containers that share a volume
    - name: watcher
      image: douglasdb/watcher
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp/lost/output/
          name: shared-volume
          #readOnly: true
    # ------------------------------------------------
    - name: writer
      image: douglasdb/writer
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp/lost/input/
          name: shared-volume