apiVersion: v1
kind: Pod

metadata:
  name: writer-pod

spec:
  volumes:
    - name: shared-volume
      hostPath:
        path: /tmp
      #emptyDir: { }
      #tmpfs as fast as possible
      # medium: Memory
  containers:
    # Same for sample section 7.6 A pod with two containers that share a volume
    #- name: camelapp-watcher
    #  image: douglasdb/appv1-emptydir-read:2.0
    #  imagePullPolicy: Always
    #  volumeMounts:
    #    - mountPath: /tmp/lost/output/
    #      name: shared-volume
    #readOnly: true
    # ------------------------------------------------
    - name: writer
      image: douglasdb/writer
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp/lost/input/
          name: shared-volume