apiVersion: batch/v1
kind: CronJob
metadata:
  name: arsenal-batch-cron
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: arsenal-batch-cron
              image: douglasdb/arsenal-batch:1.0
          restartPolicy: OnFailure
  # Every each 1 minute
  schedule: "*/1 * * * *"