apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-batch
spec:
  # default for completions and parallelism
  template:
    metadata:
      name: myapp-batch
    spec:
      containers:
        - name: myapp-batch
          image: douglasdb/myapp-batch:1.0
      restartPolicy: OnFailure
